### ISSUE TITLE
Submodule from .gitmodules is not included in repository

### ISSUE THREAD

**Issue by Gikkman** [HeatXD/chdr_cs#1]
When I tried to clone this project to check it out, I noticed the submodule (defined in `.gitmodules`) didn't get cloned automatically if you use the `--recursive` flag (`git clone --recursive ...`). I think this is because you'd need to add the submodule folder via `git add thirdparty/libchdr` for it to be included in a commit.

**Comment by Jamie-Meyer-Fontys** [comment]
Ok thank you! will review when I'm back from work!

**Comment by HeatXD** [comment]
Ok thank you! will review when im back from work!
